domain_path: C:\Users\User\Desktop\main\vitiswork\ARTY\export\ARTY\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\VIVADO\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
